apiVersion: v1
kind: Service
metadata:
  name: weather
  labels:
    app: vid
spec:
  ports:
    - port: 80
      name: weather
      targetPort: weather
  selector:
    app: vid
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  labels:
    app: vid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vid
  template:
    metadata:
      labels:
        app: vid
    spec:
      containers:
      - name: weather
        image: 692228415686.dkr.ecr.us-east-1.amazonaws.com/weather:latest
        ports:
        - containerPort: 5000
          name: weather
